global:
  scrape_interval: 15s  # Tempo de coleta de métricas

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'docker'
    dockerswarm_sd_configs:
      - host: 'unix:///var/run/docker.sock'
        role: 'tasks'

  - job_name: 'docker-containers'
    static_configs:
      - targets: ['host.docker.internal:2375']

